/**
 * @file de.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description German shell copy.
 */

import type { ShellCopy } from './types';

export const DE: ShellCopy = {
  play: 'Spielen',
  ranks: 'Ranglisten',
  options: 'Optionen',
  about: 'Über',
  aboutVersion: 'Version',
  aboutNote: 'Versionshinweis',
  aboutNoteMissing: 'Der Hinweis zu dieser Version wird mit der Veröffentlichung geschrieben.',
  aboutCredits: 'Credits',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Proprietäre Software. Alle Rechte vorbehalten.',
  settings: 'Einstellungen',
  settingsHint: 'Ton, Sprache, Steuerung und Anschluss des Assistenten.',
  modes: 'Modi',
  modeCards: {
    cpu: { title: 'Gegen den Computer', blurb: 'Eine Partie gegen die Heuristik.' },
    hotseat: { title: 'Zu zweit, ein Bildschirm', blurb: 'Die Maus wird weitergegeben.' },
    local: { title: 'Auf diesem Computer', blurb: 'Ein zweites Fenster dieser Anwendung.' },
    online: { title: 'Online', blurb: 'Einen Tisch erstellen oder beitreten.' },
    learn: { title: 'Lernen', blurb: 'Eine kurze ECO-Linie.' },
    training: { title: 'Training', blurb: 'Anhalten, ansehen, erneut spielen.' },
  },
  color: 'Farbe',
  white: 'Weiß',
  black: 'Schwarz',
  level: 'Stufe',
  line: 'Linie',
  openings: {
    C50: 'Italienische Partie',
    C60: 'Spanische Partie',
    C44: 'Schottische Partie',
    B20: 'Sizilianische Verteidigung',
    C00: 'Französische Verteidigung',
    B10: 'Caro-Kann',
    D06: 'Damengambit',
    E60: 'Königsindisch',
  },
  begin: 'Beginnen',
  openLobby: 'Die Lobby öffnen',
  back: 'Zurück',
  backModes: 'Zurück zu den Modi',
  lobby: 'Online-Lobby',
  colorHint: 'Die Farbe wird hier gewählt. Der Gast nimmt die andere.',
  create: 'Einen Tisch erstellen',
  join: 'Beitreten',
  copy: 'Kopieren',
  refused: 'Code abgelehnt',
  whiteTurn: 'Weiß ist am Zug',
  blackTurn: 'Schwarz ist am Zug',
  thinking: 'Der Computer überlegt…',
  learn: 'Lernen',
  assistant: 'Assistent',
  pause: 'Pause',
  grab: 'greifen',
  orbit: 'drehen',
  reset: 'neu starten',
  coachBanner: 'Ein Kommentar, kein Zug. Der Assistent spielt nicht.',
  noModel: 'Kein Modell ist verbunden.',
  explain: 'Die Stellung erklären',
  hint: 'Hinweis',
  ask: 'Freie Frage',
  stop: 'Stopp',
  undoMove: 'Meinen Zug zurücknehmen',
  horizon: 'Horizont',
  mistake: 'Meinen Fehler erklären',
  strategy: 'Strategie',
  objection: 'Einspruch!',
  ghostHint:
    'Der grüne Geist ist dein nächster Zug. Blau ist wieder deiner, dann Gelb. Danach Orange, dann Violett. Der Rand umgibt deine Figur. Rot markiert deinen schwachen Zug.',
  dialoguePrev: 'Zurück',
  dialogueNext: 'Weiter',
  dialogueSkip: 'Überspringen',
  objectionLesson:
    'Ich halte die Partie an. Dieser Zug überlässt dem Gegner einen Vorteil. Der rote Rand liegt auf der Figur, die du gerade gezogen hast. Der grüne Geist ist der Zug, den ich empfehle, und der grüne Rand umgibt die Figur, die ziehen soll. Du kannst zurücknehmen und es noch einmal versuchen. Ich erkläre warum.',
  trainingWelcome:
    'Hier wird gelernt, ohne die zehn Minuten. Spiele einen Zug. Wirkt er schwach, halte ich an: ein roter Rand umgibt diese Figur, und Geister zeigen die Fortsetzung. Grün, dann Blau, dann Gelb. Dieselbe Farbe umrandet die Figur, die zieht.',
  clockOn: 'Die zehn Minuten wieder einschalten',
  clockOff: 'Die zehn Minuten ausschalten',
  noAnswer: 'Das Modell hat nicht geantwortet.',
  coachModel: 'Modell',
  coachBase: 'Serveradresse',
  coachKey: 'Zugangsschlüssel, falls der Server einen verlangt',
  coachSave: 'Diesen Server speichern',
  coachChecking: 'Suche nach Ollama auf diesem Computer…',
  coachReady: 'Ollama antwortet. Der Assistent nutzt es, ohne Eingabe.',
  coachInstalled: 'Ollama ist installiert, antwortet aber noch nicht.',
  coachStart: 'Ollama starten',
  coachMissing: 'Ollama ist nicht installiert. Damit spricht der Assistent auf diesem Computer, ohne Konto.',
  coachInstall: 'Ollama herunterladen',
  coachNoModels: 'Ollama hat kein Modell. Im Terminal: ollama pull llama3.2',
  coachOther: 'Einen anderen Server nutzen',
  send: 'Senden',
  openSettings: 'Einstellungen öffnen',
  close: 'Schließen',
  resume: 'Fortsetzen',
  changeMode: 'Modus wechseln',
  leave: 'Den Tisch verlassen',
  home: 'Zurück zum Start',
  sound: 'Ton',
  sfx: 'Zuglautstärke',
  ambience: 'Umgebung',
  language: 'Sprache',
  controls: 'Steuerung',
  grabLine: 'Eine Figur greifen und absetzen.',
  orbitLine: 'Um das Brett drehen, auch mit dem Rad.',
  resetLine: 'Die Partie oder die Linie neu starten.',
  escapeKey: 'Esc',
  escapeLine: 'Pause, oder das offene Feld schließen.',
  example: 'Beispiel',
  wins: 'Siege',
  losses: 'Niederlagen',
  draws: 'Remis',
  streak: 'Serie',
  localGames: [
    'Sieg · Computer',
    'Niederlage · gleicher Bildschirm',
    'Remis · online',
    'Sieg · Eröffnung',
    'Sieg · Computer',
  ],
  onlineGames: [
    'Sieg · Tisch K7QM',
    'Niederlage · Tisch M2LP',
    'Remis · Tisch Q9AD',
    'Sieg · Tisch H4CE',
    'Niederlage · Tisch B8NR',
  ],
  exampleRanks: 'Beispiel — kein Punkte-Server.',
  localTab: 'Lokal',
  onlineTab: 'Online',
  optionsHint: 'Das Bild gilt sofort. Ton und Assistent sind in den Einstellungen.',
  preset: 'Voreinstellung',
  presets: { fluide: 'Flüssig', equilibre: 'Ausgewogen', qualite: 'Qualität', natif: 'Nativ' },
  image: 'Bild',
  resolution: 'Auflösung',
  resolutionNative: 'Nativ',
  textures: 'Figurtexturen',
  textureQuality: { low: 'Niedrig', medium: 'Normal', high: 'Hoch' },
  effects: 'Effekte',
  shadows: 'Schatten',
  ao: 'Umgebungsverdeckung',
  reflections: 'Spiegelungen des Bretts',
  bloom: 'Bloom',
  render: 'Bild',
  fps: 'Bilder/s',
  saves: 'Speicherstände',
  resumeGame: 'Partie fortsetzen',
  save: 'Speichern',
  saved: 'Partie gespeichert',
  savesHint: 'Die Unterbrechung ist die geschlossene Partie. Die anderen sind die in der Pause gespeicherten.',
  interrupted: 'Unterbrochene Partie',
  requested: 'Gespeichert',
  restore: 'Wiederherstellen',
  discard: 'Verwerfen',
  remove: 'Löschen',
  noSaves: 'Keine Partie gespeichert.',
  p2p: { waiting: 'Warten', connecting: 'Verbindung', connected: 'Verbunden', disconnected: 'Getrennt' },
};
