/**
 * @file en.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description English shell copy.
 */

import type { ShellCopy } from './types';

export const EN: ShellCopy = {
  play: 'Play',
  ranks: 'Rankings',
  options: 'Options',
  settings: 'Settings',
  settingsHint: 'Sound, language, controls and how the assistant connects.',
  modes: 'Modes',
  modeCards: {
    cpu: { title: 'Against the computer', blurb: 'A game against the heuristic.' },
    hotseat: { title: 'Two players, one screen', blurb: 'Pass the mouse.' },
    local: { title: 'On this computer', blurb: 'A second window of this application.' },
    online: { title: 'Online', blurb: 'Create or join a table.' },
    learn: { title: 'Learn', blurb: 'A short ECO line.' },
  },
  color: 'Color',
  white: 'White',
  black: 'Black',
  level: 'Level',
  line: 'Line',
  openings: {
    C50: 'Italian Game',
    C60: 'Ruy Lopez',
    C44: 'Scotch Game',
    B20: 'Sicilian Defence',
    C00: 'French Defence',
    B10: 'Caro-Kann Defence',
    D06: "Queen's Gambit",
    E60: "King's Indian Defence",
  },
  begin: 'Start',
  openLobby: 'Open the lobby',
  back: 'Back',
  backModes: 'Back to modes',
  lobby: 'Online lobby',
  colorHint: 'Color is chosen here. The guest takes the other one.',
  create: 'Create a table',
  join: 'Join',
  copy: 'Copy',
  refused: 'Code refused',
  whiteTurn: 'White to move',
  blackTurn: 'Black to move',
  thinking: 'The computer is thinking…',
  learn: 'Learn',
  assistant: 'Assistant',
  pause: 'Pause',
  grab: 'grab',
  orbit: 'orbit',
  reset: 'restart',
  coachBanner: 'A comment, not a move. The assistant does not play.',
  noModel: 'No model is connected.',
  explain: 'Explain the position',
  hint: 'Hint',
  ask: 'Free question',
  send: 'Send',
  openSettings: 'Open settings',
  close: 'Close',
  resume: 'Resume',
  changeMode: 'Change mode',
  leave: 'Leave the table',
  home: 'Back home',
  sound: 'Sound',
  sfx: 'Move volume',
  ambience: 'Ambience',
  language: 'Language',
  controls: 'Controls',
  grabLine: 'Grab a piece and set it down.',
  orbitLine: 'Orbit the board, including the wheel.',
  resetLine: 'Restart the game or the line.',
  escapeKey: 'Esc',
  escapeLine: 'Pause, or close the open panel.',
  example: 'example',
  wins: 'Wins',
  losses: 'Losses',
  draws: 'Draws',
  streak: 'Streak',
  localGames: ['Win · computer', 'Loss · same screen', 'Draw · online', 'Win · opening', 'Win · computer'],
  onlineGames: [
    'Win · table K7QM',
    'Loss · table M2LP',
    'Draw · table Q9AD',
    'Win · table H4CE',
    'Loss · table B8NR',
  ],
  exampleRanks: 'Example — no score server.',
  localTab: 'Local',
  onlineTab: 'Online',
  optionsHint: 'The picture updates at once. Sound and the assistant are in Settings.',
  preset: 'Preset',
  presets: { fluide: 'Smooth', equilibre: 'Balanced', qualite: 'Quality', natif: 'Native' },
  image: 'Picture',
  resolution: 'Resolution',
  resolutionNative: 'Native',
  textures: 'Piece textures',
  textureQuality: { low: 'Low', medium: 'Normal', high: 'High' },
  effects: 'Effects',
  shadows: 'Shadows',
  ao: 'Ambient occlusion',
  reflections: 'Board reflections',
  bloom: 'Bloom',
  render: 'Render',
  fps: 'fps',
  p2p: { waiting: 'Waiting', connecting: 'Connecting', connected: 'Connected', disconnected: 'Disconnected' },
};
