/**
 * @file en.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description English shell copy.
 */

import type { ShellCopy } from './types';

export const EN: ShellCopy = {
  play: 'Play',
  ranks: 'Rankings',
  options: 'Options',
  about: 'About',
  aboutVersion: 'Version',
  aboutNote: 'Release note',
  aboutNoteMissing: 'The note for this version is written with the release.',
  aboutCredits: 'Credits',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Proprietary software. All rights reserved.',
  settings: 'Settings',
  settingsHint: 'Sound, language, controls and how the assistant connects.',
  modes: 'Modes',
  modeCards: {
    cpu: { title: 'Against the computer', blurb: 'A game against the heuristic.' },
    hotseat: { title: 'Two players, one screen', blurb: 'Pass the mouse.' },
    local: { title: 'On this computer', blurb: 'A second window of this application.' },
    online: { title: 'Online', blurb: 'Create or join a table.' },
    learn: { title: 'Learn', blurb: 'A short ECO line.' },
    training: { title: 'Training', blurb: 'Stop, review, play again.' },
  },
  color: 'Color',
  white: 'White',
  black: 'Black',
  level: 'Level',
  line: 'Line',
  openings: {
    C50: 'Italian Game',
    C60: 'Ruy Lopez',
    C44: 'Scotch Game',
    B20: 'Sicilian Defence',
    C00: 'French Defence',
    B10: 'Caro-Kann Defence',
    D06: "Queen's Gambit",
    E60: "King's Indian Defence",
  },
  begin: 'Start',
  openLobby: 'Open the lobby',
  back: 'Back',
  backModes: 'Back to modes',
  lobby: 'Online lobby',
  colorHint: 'Color is chosen here. The guest takes the other one.',
  create: 'Create a table',
  join: 'Join',
  copy: 'Copy',
  refused: 'Code refused',
  tableMissing: 'Table not found or full',
  whiteTurn: 'White to move',
  blackTurn: 'Black to move',
  thinking: 'The computer is thinking…',
  learn: 'Learn',
  assistant: 'Assistant',
  pause: 'Pause',
  grab: 'grab',
  orbit: 'orbit',
  reset: 'restart',
  coachBanner: 'A comment, not a move. The assistant does not play.',
  noModel: 'No model is connected.',
  explain: 'Explain the position',
  hint: 'Hint',
  ask: 'Free question',
  stop: 'Stop',
  undoMove: 'Undo my move',
  horizon: 'Horizon',
  mistake: 'Explain my mistake',
  strategy: 'Strategy',
  objection: 'Objection!',
  ghostHint:
    'The green ghost is your next move. Blue is yours after that, then yellow. Further on: orange, then violet. The outline circles your piece. Red marks your weak move.',
  dialoguePrev: 'Previous',
  dialogueNext: 'Next',
  dialogueSkip: 'Skip',
  objectionLesson:
    'I am stopping the game. That move leaves the opponent better. The red outline is on the piece you just played. The green ghost is the move I recommend, and the green outline is on the piece that should move. You can undo and try again. I will explain why.',
  trainingWelcome:
    'This is for learning, without the ten minutes. Play a move. If I think it is weak, I stop the game: a red outline circles that piece, and ghosts show the follow-up. Green, then blue, then yellow. The same color outlines the piece that moves.',
  clockOn: 'Turn the ten minutes back on',
  clockOff: 'Turn the ten minutes off',
  noAnswer: 'The model did not answer.',
  coachModel: 'Model',
  coachBase: 'Server address',
  coachKey: 'Access key, if the server asks for one',
  coachSave: 'Save this server',
  coachChecking: 'Looking for Ollama on this computer…',
  coachReady: 'Ollama is answering. The assistant uses it, with nothing to type.',
  coachInstalled: 'Ollama is installed, but it is not answering yet.',
  coachStart: 'Start Ollama',
  coachMissing: 'Ollama is not installed. It lets the assistant speak on this computer, without an account.',
  coachInstall: 'Download Ollama',
  coachNoModels: 'Ollama has no model. In a terminal: ollama pull llama3.2',
  coachOther: 'Use another server',
  send: 'Send',
  openSettings: 'Open settings',
  close: 'Close',
  resume: 'Resume',
  changeMode: 'Change mode',
  leave: 'Leave the table',
  home: 'Back home',
  sound: 'Sound',
  sfx: 'Move volume',
  ambience: 'Ambience',
  language: 'Language',
  controls: 'Controls',
  grabLine: 'Grab a piece and set it down.',
  orbitLine: 'Orbit the board, including the wheel.',
  resetLine: 'Restart the game or the line.',
  escapeKey: 'Esc',
  escapeLine: 'Pause, or close the open panel.',
  example: 'example',
  wins: 'Wins',
  losses: 'Losses',
  draws: 'Draws',
  streak: 'Streak',
  localGames: ['Win · computer', 'Loss · same screen', 'Draw · online', 'Win · opening', 'Win · computer'],
  onlineGames: [
    'Win · table K7QM',
    'Loss · table M2LP',
    'Draw · table Q9AD',
    'Win · table H4CE',
    'Loss · table B8NR',
  ],
  exampleRanks: 'Example — no score server.',
  localTab: 'Local',
  onlineTab: 'Online',
  optionsHint: 'The picture updates at once. Sound and the assistant are in Settings.',
  setChoice: 'Set',
  sets: { atelier: 'Studio', salon: 'Salon', club: 'Club' },
  preset: 'Preset',
  presets: { fluide: 'Smooth', equilibre: 'Balanced', qualite: 'Quality', natif: 'Native' },
  image: 'Picture',
  resolution: 'Resolution',
  resolutionNative: 'Native',
  textures: 'Piece textures',
  textureQuality: { low: 'Low', medium: 'Normal', high: 'High' },
  effects: 'Effects',
  shadows: 'Shadows',
  shadowOff: 'Off',
  shadowHard: 'Hard',
  shadowSoft: 'Soft',
  upscale: 'Upscale',
  upscaleOff: 'Off',
  upscaleQuality: 'Quality',
  upscalePerformance: 'Performance',
  ao: 'Ambient occlusion',
  reflections: 'Board reflections',
  bloom: 'Bloom',
  render: 'Render',
  fps: 'fps',
  saves: 'Saves',
  resumeGame: 'Resume the game',
  save: 'Save',
  saved: 'Game saved',
  savesHint: 'The interrupted game is the one you closed. The others are the ones you saved from pause.',
  interrupted: 'Interrupted game',
  requested: 'Saved',
  restore: 'Restore',
  discard: 'Dismiss',
  remove: 'Delete',
  noSaves: 'No saved game.',
  p2p: { waiting: 'Waiting', connecting: 'Connecting', connected: 'Connected', disconnected: 'Disconnected' },
};
