/**
 * @file es.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Spanish shell copy.
 */

import type { ShellCopy } from './types';

export const ES: ShellCopy = {
  play: 'Jugar',
  ranks: 'Clasificaciones',
  options: 'Opciones',
  about: 'Acerca de',
  aboutVersion: 'Versión',
  aboutNote: 'Nota de la versión',
  aboutNoteMissing: 'La nota de esta versión se escribe con la publicación.',
  aboutCredits: 'Créditos',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Software propietario. Todos los derechos reservados.',
  settings: 'Ajustes',
  settingsHint: 'Sonido, idioma, controles y conexión del asistente.',
  modes: 'Modos',
  modeCards: {
    cpu: { title: 'Contra el ordenador', blurb: 'Una partida contra la heurística.' },
    hotseat: { title: 'Dos, la misma pantalla', blurb: 'Se pasa el ratón.' },
    local: { title: 'En este ordenador', blurb: 'Una segunda ventana de esta aplicación.' },
    online: { title: 'En línea', blurb: 'Crear una mesa o unirse.' },
    learn: { title: 'Aprender', blurb: 'Una línea ECO corta.' },
    training: { title: 'Entrenamiento', blurb: 'Parar, revisar, volver a jugar.' },
  },
  color: 'Color',
  white: 'Blancas',
  black: 'Negras',
  level: 'Nivel',
  line: 'Línea',
  openings: {
    C50: 'Apertura italiana',
    C60: 'Española',
    C44: 'Escocesa',
    B20: 'Siciliana',
    C00: 'Francesa',
    B10: 'Caro-Kann',
    D06: 'Gambito de dama',
    E60: 'India de rey',
  },
  begin: 'Empezar',
  openLobby: 'Abrir el salón',
  back: 'Volver',
  backModes: 'Volver a los modos',
  lobby: 'Salón en línea',
  colorHint: 'El color se elige aquí. El invitado toma el otro.',
  create: 'Crear una mesa',
  join: 'Unirse',
  copy: 'Copiar',
  refused: 'Código rechazado',
  tableMissing: 'Mesa no encontrada o llena',
  whiteTurn: 'Juegan las blancas',
  blackTurn: 'Juegan las negras',
  thinking: 'El ordenador está pensando…',
  learn: 'Aprender',
  assistant: 'Asistente',
  pause: 'Pausa',
  grab: 'tomar',
  orbit: 'orbitar',
  reset: 'volver a empezar',
  coachBanner: 'Un comentario, no una jugada. El asistente no juega.',
  noModel: 'Ningún modelo está conectado.',
  explain: 'Explicar la posición',
  hint: 'Pista',
  ask: 'Pregunta libre',
  stop: 'Parar',
  undoMove: 'Deshacer mi jugada',
  horizon: 'Horizonte',
  mistake: 'Explicar mi error',
  strategy: 'Estrategia',
  objection: '¡Objeción!',
  objectionLine: 'No es la jugada más limpia.',
  ghostHint:
    'El fantasma verde es tu próxima jugada. El azul también es tuya, luego el amarillo. Más allá: naranja, luego violeta. El borde rodea tu pieza. El rojo marca tu jugada débil.',
  dialoguePrev: 'Anterior',
  dialogueNext: 'Siguiente',
  dialogueSkip: 'Pasar',
  objectionLesson:
    'Paro la partida. Esa jugada deja ventaja al rival. El borde rojo está en la pieza que acabas de jugar. El fantasma verde es la jugada que recomiendo, y el borde verde rodea la pieza que debe salir. Puedes deshacer y probar otra vez. Explico por qué.',
  trainingWelcome:
    'Aquí se aprende, sin los diez minutos. Juega una jugada. Si la veo débil, paro la partida: un borde rojo rodea esa pieza, y unos fantasmas muestran la continuación. Verde, luego azul, luego amarillo. El mismo color rodea la pieza que sale.',
  clockOn: 'Volver a poner los diez minutos',
  clockOff: 'Quitar los diez minutos',
  noAnswer: 'El modelo no ha respondido.',
  coachModel: 'Modelo',
  coachBase: 'Dirección del servidor',
  coachKey: 'Clave de acceso, si el servidor la pide',
  coachSave: 'Guardar este servidor',
  coachChecking: 'Buscando Ollama en este ordenador…',
  coachReady: 'Ollama responde. El asistente lo usa, sin nada que escribir.',
  coachInstalled: 'Ollama está instalado, pero todavía no responde.',
  coachStart: 'Iniciar Ollama',
  coachMissing: 'Ollama no está instalado. Hace hablar al asistente en este ordenador, sin cuenta.',
  coachInstall: 'Descargar Ollama',
  coachNoModels: 'Ollama no tiene un modelo. En un terminal: ollama pull llama3.2',
  coachOther: 'Usar otro servidor',
  send: 'Enviar',
  openSettings: 'Abrir los ajustes',
  close: 'Cerrar',
  resume: 'Reanudar',
  changeMode: 'Cambiar de modo',
  leave: 'Dejar la mesa',
  home: 'Volver al inicio',
  won: 'Ganada',
  lost: 'Perdida',
  drawn: 'Tablas',
  mateWhite: 'Las blancas están en jaque mate.',
  mateBlack: 'Las negras están en jaque mate.',
  flagWhite: 'Las blancas perdieron por tiempo.',
  flagBlack: 'Las negras perdieron por tiempo.',
  stalemateLine: 'Ahogado. Ninguna jugada legal.',
  insufficientLine: 'Material insuficiente.',
  agreedLine: 'Tablas aceptadas.',
  resignWhite: 'Las blancas abandonaron.',
  resignBlack: 'Las negras abandonaron.',
  resign: 'Abandonar',
  offerDraw: 'Proponer tablas',
  acceptDraw: 'Aceptar',
  refuseDraw: 'Rechazar',
  drawOfferTitle: 'Proponer tablas',
  drawOfferCpu: 'El ordenador acepta si la evaluación está dentro de ±50 centipeones.',
  drawOfferPeer: 'El otro bando ve esta oferta.',
  drawRefused: 'Tablas rechazadas.',
  cancel: 'Cancelar',
  lineDone: 'La línea ha terminado.',
  seeBoard: 'Ver el tablero',
  replay: 'Otra vez',
  result: 'Resultado',
  sound: 'Sonido',
  sfx: 'Volumen de las jugadas',
  ambience: 'Ambiente',
  language: 'Idioma',
  controls: 'Controles',
  grabLine: 'Tomar una pieza y soltarla.',
  orbitLine: 'Girar alrededor del tablero, rueda incluida.',
  resetLine: 'Volver a empezar la partida o la línea.',
  escapeKey: 'Esc',
  escapeLine: 'Pausa, o cerrar el panel abierto.',
  example: 'ejemplo',
  wins: 'Victorias',
  losses: 'Derrotas',
  draws: 'Tablas',
  streak: 'Racha',
  localGames: [
    'Victoria · ordenador',
    'Derrota · misma pantalla',
    'Tablas · en línea',
    'Victoria · apertura',
    'Victoria · ordenador',
  ],
  onlineGames: [
    'Victoria · mesa K7QM',
    'Derrota · mesa M2LP',
    'Tablas · mesa Q9AD',
    'Victoria · mesa H4CE',
    'Derrota · mesa B8NR',
  ],
  exampleRanks: 'Ejemplo — no hay servidor de puntuaciones.',
  localTab: 'Local',
  onlineTab: 'En línea',
  optionsHint: 'La imagen se aplica al momento. El sonido y el asistente están en Ajustes.',
  setChoice: 'Ambiente',
  sets: { atelier: 'Taller', salon: 'Salón', club: 'Club', jardin: 'Jardín', terrasse: 'Terraza' },
  preset: 'Preajuste',
  presets: { fluide: 'Fluido', equilibre: 'Equilibrado', qualite: 'Calidad', natif: 'Nativo' },
  image: 'Imagen',
  resolution: 'Resolución',
  resolutionNative: 'Nativo',
  textures: 'Texturas de las piezas',
  textureQuality: { low: 'Baja', medium: 'Normal', high: 'Alta' },
  effects: 'Efectos',
  shadows: 'Sombras',
  shadowOff: 'Sin sombras',
  shadowHard: 'Dura',
  shadowSoft: 'Suave',
  upscale: 'Upscale',
  upscaleOff: 'Sin',
  upscaleQuality: 'Calidad',
  upscalePerformance: 'Rendimiento',
  ao: 'Oclusión ambiental',
  reflections: 'Reflejos del tablero',
  bloom: 'Bloom',
  render: 'Render',
  fps: 'fps',
  saves: 'Partidas guardadas',
  resumeGame: 'Reanudar la partida',
  save: 'Guardar',
  saved: 'Partida guardada',
  savesHint: 'La interrupción es la partida cerrada. Las otras son las pedidas en pausa.',
  interrupted: 'Partida interrumpida',
  requested: 'Pedidas',
  restore: 'Restaurar',
  discard: 'Descartar',
  remove: 'Eliminar',
  noSaves: 'Ninguna partida guardada.',
  p2p: { waiting: 'En espera', connecting: 'Conexión', connected: 'Conectado', disconnected: 'Desconectado' },
};
