/**
 * @file es.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Spanish shell copy.
 */

import type { ShellCopy } from './types';

export const ES: ShellCopy = {
  play: 'Jugar',
  ranks: 'Clasificaciones',
  options: 'Opciones',
  about: 'Acerca de',
  aboutVersion: 'Versión',
  aboutNote: 'Nota de la versión',
  aboutNoteMissing: 'La nota de esta versión se escribe con la publicación.',
  aboutCredits: 'Créditos',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Software propietario. Todos los derechos reservados.',
  settings: 'Ajustes',
  settingsHint: 'Sonido, idioma, controles y conexión del asistente.',
  modes: 'Modos',
  modeCards: {
    cpu: { title: 'Contra el ordenador', blurb: 'Una partida contra la heurística.' },
    hotseat: { title: 'Dos, la misma pantalla', blurb: 'Se pasa el ratón.' },
    local: { title: 'En este ordenador', blurb: 'Una segunda ventana de esta aplicación.' },
    online: { title: 'En línea', blurb: 'Crear una mesa o unirse.' },
    learn: { title: 'Aprender', blurb: 'Una línea ECO corta.' },
  },
  color: 'Color',
  white: 'Blancas',
  black: 'Negras',
  level: 'Nivel',
  line: 'Línea',
  openings: {
    C50: 'Apertura italiana',
    C60: 'Española',
    C44: 'Escocesa',
    B20: 'Siciliana',
    C00: 'Francesa',
    B10: 'Caro-Kann',
    D06: 'Gambito de dama',
    E60: 'India de rey',
  },
  begin: 'Empezar',
  openLobby: 'Abrir el salón',
  back: 'Volver',
  backModes: 'Volver a los modos',
  lobby: 'Salón en línea',
  colorHint: 'El color se elige aquí. El invitado toma el otro.',
  create: 'Crear una mesa',
  join: 'Unirse',
  copy: 'Copiar',
  refused: 'Código rechazado',
  whiteTurn: 'Juegan las blancas',
  blackTurn: 'Juegan las negras',
  thinking: 'El ordenador está pensando…',
  learn: 'Aprender',
  assistant: 'Asistente',
  pause: 'Pausa',
  grab: 'tomar',
  orbit: 'orbitar',
  reset: 'volver a empezar',
  coachBanner: 'Un comentario, no una jugada. El asistente no juega.',
  noModel: 'Ningún modelo está conectado.',
  explain: 'Explicar la posición',
  hint: 'Pista',
  ask: 'Pregunta libre',
  send: 'Enviar',
  openSettings: 'Abrir los ajustes',
  close: 'Cerrar',
  resume: 'Reanudar',
  changeMode: 'Cambiar de modo',
  leave: 'Dejar la mesa',
  home: 'Volver al inicio',
  sound: 'Sonido',
  sfx: 'Volumen de las jugadas',
  ambience: 'Ambiente',
  language: 'Idioma',
  controls: 'Controles',
  grabLine: 'Tomar una pieza y soltarla.',
  orbitLine: 'Girar alrededor del tablero, rueda incluida.',
  resetLine: 'Volver a empezar la partida o la línea.',
  escapeKey: 'Esc',
  escapeLine: 'Pausa, o cerrar el panel abierto.',
  example: 'ejemplo',
  wins: 'Victorias',
  losses: 'Derrotas',
  draws: 'Tablas',
  streak: 'Racha',
  localGames: [
    'Victoria · ordenador',
    'Derrota · misma pantalla',
    'Tablas · en línea',
    'Victoria · apertura',
    'Victoria · ordenador',
  ],
  onlineGames: [
    'Victoria · mesa K7QM',
    'Derrota · mesa M2LP',
    'Tablas · mesa Q9AD',
    'Victoria · mesa H4CE',
    'Derrota · mesa B8NR',
  ],
  exampleRanks: 'Ejemplo — no hay servidor de puntuaciones.',
  localTab: 'Local',
  onlineTab: 'En línea',
  optionsHint: 'La imagen se aplica al momento. El sonido y el asistente están en Ajustes.',
  preset: 'Preajuste',
  presets: { fluide: 'Fluido', equilibre: 'Equilibrado', qualite: 'Calidad', natif: 'Nativo' },
  image: 'Imagen',
  resolution: 'Resolución',
  resolutionNative: 'Nativo',
  textures: 'Texturas de las piezas',
  textureQuality: { low: 'Baja', medium: 'Normal', high: 'Alta' },
  effects: 'Efectos',
  shadows: 'Sombras',
  ao: 'Oclusión ambiental',
  reflections: 'Reflejos del tablero',
  bloom: 'Bloom',
  render: 'Render',
  fps: 'fps',
  saves: 'Partidas guardadas',
  resumeGame: 'Reanudar la partida',
  save: 'Guardar',
  saved: 'Partida guardada',
  savesHint: 'La interrupción es la partida cerrada. Las otras son las pedidas en pausa.',
  interrupted: 'Partida interrumpida',
  requested: 'Pedidas',
  restore: 'Restaurar',
  discard: 'Descartar',
  remove: 'Eliminar',
  noSaves: 'Ninguna partida guardada.',
  p2p: { waiting: 'En espera', connecting: 'Conexión', connected: 'Conectado', disconnected: 'Desconectado' },
};
