/**
 * @file fr.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description French shell copy. Source catalog for the other languages.
 */

import type { ShellCopy } from './types';

export const FR: ShellCopy = {
  play: 'Jouer',
  ranks: 'Classements',
  options: 'Options',
  about: 'À propos',
  aboutVersion: 'Version',
  aboutNote: 'Note de release',
  aboutNoteMissing: 'La note de cette version sera écrite avec la release.',
  aboutCredits: 'Crédits',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Logiciel propriétaire. Tous droits réservés.',
  settings: 'Paramètres',
  settingsHint: 'Son, langue, contrôles et branchement de l’assistant.',
  modes: 'Modes',
  modeCards: {
    cpu: { title: 'Contre l’ordinateur', blurb: 'Une partie contre l’heuristique.' },
    hotseat: { title: 'À deux, même écran', blurb: 'On se passe la souris.' },
    local: { title: 'Sur cet ordinateur', blurb: 'Une seconde fenêtre de cette application.' },
    online: { title: 'En ligne', blurb: 'Créer ou rejoindre une table.' },
    learn: { title: 'Apprendre', blurb: 'Une courte ligne ECO.' },
  },
  color: 'Couleur',
  white: 'Blancs',
  black: 'Noirs',
  level: 'Niveau',
  line: 'Ligne',
  openings: {
    C50: 'Partie italienne',
    C60: 'Espagnole',
    C44: 'Écossaise',
    B20: 'Sicilienne',
    C00: 'Française',
    B10: 'Caro-Kann',
    D06: 'Gambit de la dame',
    E60: 'Indienne du roi',
  },
  begin: 'Commencer',
  openLobby: 'Ouvrir le salon',
  back: 'Retour',
  backModes: 'Retour aux modes',
  lobby: 'Salon en ligne',
  colorHint: 'La couleur se choisit ici. L’invité prend l’autre.',
  create: 'Créer une table',
  join: 'Rejoindre',
  copy: 'Copier',
  refused: 'Code refusé',
  whiteTurn: 'Les blancs jouent',
  blackTurn: 'Les noirs jouent',
  thinking: 'L’ordinateur réfléchit…',
  learn: 'Apprendre',
  assistant: 'Assistant',
  pause: 'Pause',
  grab: 'saisir',
  orbit: 'orbiter',
  reset: 'recommencer',
  coachBanner: 'Commentaire, pas un coup. L’assistant ne joue pas.',
  noModel: 'Aucun modèle n’est branché.',
  explain: 'Expliquer la position',
  hint: 'Indice',
  ask: 'Question libre',
  send: 'Envoyer',
  openSettings: 'Ouvrir les paramètres',
  close: 'Fermer',
  resume: 'Reprendre',
  changeMode: 'Changer de mode',
  leave: 'Quitter la table',
  home: 'Retour à l’accueil',
  sound: 'Son',
  sfx: 'Volume des coups',
  ambience: 'Volume d’ambiance',
  language: 'Langue',
  controls: 'Contrôles',
  grabLine: 'Saisir une pièce et la poser.',
  orbitLine: 'Tourner autour du plateau, molette comprise.',
  resetLine: 'Recommencer la partie ou la ligne.',
  escapeKey: 'Échap',
  escapeLine: 'Pause, ou fermer le panneau ouvert.',
  example: 'exemple',
  wins: 'Victoires',
  losses: 'Défaites',
  draws: 'Nuls',
  streak: 'Série',
  localGames: [
    'Victoire · ordinateur',
    'Défaite · même écran',
    'Nulle · en ligne',
    'Victoire · ouverture',
    'Victoire · ordinateur',
  ],
  onlineGames: [
    'Victoire · table K7QM',
    'Défaite · table M2LP',
    'Nulle · table Q9AD',
    'Victoire · table H4CE',
    'Défaite · table B8NR',
  ],
  exampleRanks: 'Exemple — aucun serveur de scores.',
  localTab: 'Local',
  onlineTab: 'En ligne',
  optionsHint: 'Le rendu s’applique tout de suite. Le son et l’assistant sont dans Paramètres.',
  preset: 'Préréglage',
  presets: { fluide: 'Fluide', equilibre: 'Équilibré', qualite: 'Qualité', natif: 'Natif' },
  image: 'Image',
  resolution: 'Résolution',
  resolutionNative: 'Natif',
  textures: 'Textures des pièces',
  textureQuality: { low: 'Basse', medium: 'Normale', high: 'Haute' },
  effects: 'Effets',
  shadows: 'Ombres',
  ao: 'Occlusion ambiante',
  reflections: 'Reflets du plateau',
  bloom: 'Bloom',
  render: 'Rendu',
  fps: 'img/s',
  saves: 'Sauvegardes',
  resumeGame: 'Reprendre la partie',
  save: 'Sauvegarder',
  saved: 'Partie sauvegardée',
  savesHint: 'L’interruption est la partie fermée. Les autres sont celles demandées en pause.',
  interrupted: 'Partie interrompue',
  requested: 'Demandées',
  restore: 'Restaurer',
  discard: 'Écarter',
  remove: 'Supprimer',
  noSaves: 'Aucune partie gardée.',
  p2p: { waiting: 'En attente', connecting: 'Connexion', connected: 'Connecté', disconnected: 'Déconnecté' },
};
