/**
 * @file fr.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description French shell copy. Source catalog for the other languages.
 */

import type { ShellCopy } from './types';

export const FR: ShellCopy = {
  play: 'Jouer',
  ranks: 'Classements',
  options: 'Options',
  about: 'À propos',
  aboutVersion: 'Version',
  aboutNote: 'Note de release',
  aboutNoteMissing: 'La note de cette version sera écrite avec la release.',
  aboutCredits: 'Crédits',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Logiciel propriétaire. Tous droits réservés.',
  settings: 'Paramètres',
  settingsHint: 'Son, langue, contrôles et branchement de l’assistant.',
  modes: 'Modes',
  modeCards: {
    cpu: { title: 'Contre l’ordinateur', blurb: 'Une partie contre l’heuristique.' },
    hotseat: { title: 'À deux, même écran', blurb: 'On se passe la souris.' },
    local: { title: 'Sur cet ordinateur', blurb: 'Une seconde fenêtre de cette application.' },
    online: { title: 'En ligne', blurb: 'Créer ou rejoindre une table.' },
    learn: { title: 'Apprendre', blurb: 'Une courte ligne ECO.' },
    training: { title: 'Entraînement', blurb: 'Arrêter, revoir, rejouer.' },
  },
  color: 'Couleur',
  white: 'Blancs',
  black: 'Noirs',
  level: 'Niveau',
  line: 'Ligne',
  openings: {
    C50: 'Partie italienne',
    C60: 'Espagnole',
    C44: 'Écossaise',
    B20: 'Sicilienne',
    C00: 'Française',
    B10: 'Caro-Kann',
    D06: 'Gambit de la dame',
    E60: 'Indienne du roi',
  },
  begin: 'Commencer',
  openLobby: 'Ouvrir le salon',
  back: 'Retour',
  backModes: 'Retour aux modes',
  lobby: 'Salon en ligne',
  colorHint: 'La couleur se choisit ici. L’invité prend l’autre.',
  create: 'Créer une table',
  join: 'Rejoindre',
  copy: 'Copier',
  refused: 'Code refusé',
  whiteTurn: 'Les blancs jouent',
  blackTurn: 'Les noirs jouent',
  thinking: 'L’ordinateur réfléchit…',
  learn: 'Apprendre',
  assistant: 'Assistant',
  pause: 'Pause',
  grab: 'saisir',
  orbit: 'orbiter',
  reset: 'recommencer',
  coachBanner: 'Commentaire, pas un coup. L’assistant ne joue pas.',
  noModel: 'Aucun modèle n’est branché.',
  explain: 'Expliquer la position',
  hint: 'Indice',
  ask: 'Question libre',
  stop: 'Stop',
  undoMove: 'Annuler mon coup',
  horizon: 'Horizon',
  mistake: 'Expliquer mon erreur',
  strategy: 'Stratégie',
  objection: 'Objection !',
  ghostHint:
    'Le fantôme vert est ton prochain coup. Le bleu est encore le tien, puis le jaune. S’il y en a plus : orange, puis violet. Le liseré entoure ta pièce qui part. Le rouge marque ton coup faible.',
  dialoguePrev: 'Précédent',
  dialogueNext: 'Suivant',
  dialogueSkip: 'Passer',
  objectionLesson:
    'J’arrête la partie. Ce coup laisse un avantage à l’adversaire. Le liseré rouge est sur la pièce que tu viens de jouer. Le fantôme vert est le coup que je recommande, et le liseré vert entoure la pièce qui doit partir. Tu peux annuler pour réessayer. J’explique pourquoi.',
  trainingWelcome:
    'Ici on apprend, sans les 10 minutes. Joue un coup. Si je le trouve faible, je coupe la partie : un liseré rouge entoure cette pièce, et des fantômes montrent la suite. Vert, puis bleu, puis jaune. Le liseré de la même couleur entoure la pièce qui part.',
  clockOn: 'Remettre les 10 minutes',
  clockOff: 'Couper les 10 minutes',
  noAnswer: 'Le modèle n’a pas répondu.',
  coachModel: 'Modèle',
  coachBase: 'Adresse du serveur',
  coachKey: 'Clé d’accès, si le serveur en demande une',
  coachSave: 'Enregistrer ce serveur',
  coachChecking: 'Recherche d’Ollama sur cet ordinateur…',
  coachReady: 'Ollama répond. L’assistant l’utilise, sans rien à saisir.',
  coachInstalled: 'Ollama est installé, mais il ne répond pas encore.',
  coachStart: 'Lancer Ollama',
  coachMissing: 'Ollama n’est pas installé. Il fait parler l’assistant sur cet ordinateur, sans compte.',
  coachInstall: 'Télécharger Ollama',
  coachNoModels: 'Ollama n’a aucun modèle. Dans un terminal : ollama pull llama3.2',
  coachOther: 'Utiliser un autre serveur',
  send: 'Envoyer',
  openSettings: 'Ouvrir les paramètres',
  close: 'Fermer',
  resume: 'Reprendre',
  changeMode: 'Changer de mode',
  leave: 'Quitter la table',
  home: 'Retour à l’accueil',
  sound: 'Son',
  sfx: 'Volume des coups',
  ambience: 'Volume d’ambiance',
  language: 'Langue',
  controls: 'Contrôles',
  grabLine: 'Saisir une pièce et la poser.',
  orbitLine: 'Tourner autour du plateau, molette comprise.',
  resetLine: 'Recommencer la partie ou la ligne.',
  escapeKey: 'Échap',
  escapeLine: 'Pause, ou fermer le panneau ouvert.',
  example: 'exemple',
  wins: 'Victoires',
  losses: 'Défaites',
  draws: 'Nuls',
  streak: 'Série',
  localGames: [
    'Victoire · ordinateur',
    'Défaite · même écran',
    'Nulle · en ligne',
    'Victoire · ouverture',
    'Victoire · ordinateur',
  ],
  onlineGames: [
    'Victoire · table K7QM',
    'Défaite · table M2LP',
    'Nulle · table Q9AD',
    'Victoire · table H4CE',
    'Défaite · table B8NR',
  ],
  exampleRanks: 'Exemple — aucun serveur de scores.',
  localTab: 'Local',
  onlineTab: 'En ligne',
  optionsHint: 'Le rendu s’applique tout de suite. Le son et l’assistant sont dans Paramètres.',
  preset: 'Préréglage',
  presets: { fluide: 'Fluide', equilibre: 'Équilibré', qualite: 'Qualité', natif: 'Natif' },
  image: 'Image',
  resolution: 'Résolution',
  resolutionNative: 'Natif',
  textures: 'Textures des pièces',
  textureQuality: { low: 'Basse', medium: 'Normale', high: 'Haute' },
  effects: 'Effets',
  shadows: 'Ombres',
  ao: 'Occlusion ambiante',
  reflections: 'Reflets du plateau',
  bloom: 'Bloom',
  render: 'Rendu',
  fps: 'img/s',
  saves: 'Sauvegardes',
  resumeGame: 'Reprendre la partie',
  save: 'Sauvegarder',
  saved: 'Partie sauvegardée',
  savesHint: 'L’interruption est la partie fermée. Les autres sont celles demandées en pause.',
  interrupted: 'Partie interrompue',
  requested: 'Demandées',
  restore: 'Restaurer',
  discard: 'Écarter',
  remove: 'Supprimer',
  noSaves: 'Aucune partie gardée.',
  p2p: { waiting: 'En attente', connecting: 'Connexion', connected: 'Connecté', disconnected: 'Déconnecté' },
};
