/**
 * @file it.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Italian shell copy.
 */

import type { ShellCopy } from './types';

export const IT: ShellCopy = {
  play: 'Gioca',
  ranks: 'Classifiche',
  options: 'Opzioni',
  about: 'Informazioni',
  aboutVersion: 'Versione',
  aboutNote: 'Nota di rilascio',
  aboutNoteMissing: 'La nota di questa versione si scrive con la pubblicazione.',
  aboutCredits: 'Crediti',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Software proprietario. Tutti i diritti riservati.',
  settings: 'Impostazioni',
  settingsHint: 'Suono, lingua, controlli e collegamento dell’assistente.',
  modes: 'Modi',
  modeCards: {
    cpu: { title: 'Contro il computer', blurb: 'Una partita contro l’euristica.' },
    hotseat: { title: 'In due, stesso schermo', blurb: 'Ci si passa il mouse.' },
    local: { title: 'Su questo computer', blurb: 'Una seconda finestra di questa applicazione.' },
    online: { title: 'In rete', blurb: 'Creare un tavolo o unirsi.' },
    learn: { title: 'Imparare', blurb: 'Una breve linea ECO.' },
    training: { title: 'Allenamento', blurb: 'Fermare, rivedere, rigiocare.' },
  },
  color: 'Colore',
  white: 'Bianchi',
  black: 'Neri',
  level: 'Livello',
  line: 'Linea',
  openings: {
    C50: 'Partita italiana',
    C60: 'Spagnola',
    C44: 'Scozzese',
    B20: 'Siciliana',
    C00: 'Francese',
    B10: 'Caro-Kann',
    D06: 'Gambetto di donna',
    E60: 'Indiana di re',
  },
  begin: 'Iniziare',
  openLobby: 'Aprire il salone',
  back: 'Indietro',
  backModes: 'Torna ai modi',
  lobby: 'Salone in rete',
  colorHint: 'Il colore si sceglie qui. L’ospite prende l’altro.',
  create: 'Creare un tavolo',
  join: 'Unirsi',
  copy: 'Copiare',
  refused: 'Codice rifiutato',
  tableMissing: 'Tavolo introvabile o pieno',
  whiteTurn: 'Tocca al Bianco',
  blackTurn: 'Tocca al Nero',
  thinking: 'Il computer sta pensando…',
  learn: 'Imparare',
  assistant: 'Assistente',
  pause: 'Pausa',
  grab: 'prendere',
  orbit: 'ruotare',
  reset: 'ricominciare',
  coachBanner: 'Un commento, non una mossa. L’assistente non gioca.',
  noModel: 'Nessun modello è collegato.',
  explain: 'Spiegare la posizione',
  hint: 'Suggerimento',
  ask: 'Domanda libera',
  stop: 'Stop',
  undoMove: 'Annulla la mia mossa',
  horizon: 'Orizzonte',
  mistake: 'Spiega il mio errore',
  strategy: 'Strategia',
  objection: 'Obiezione!',
  objectionLine: 'Non è la mossa più netta.',
  ghostHint:
    'Il fantasma verde è la tua prossima mossa. Il blu è ancora tua, poi il giallo. Oltre: arancione, poi violetto. Il bordo contorna il tuo pezzo. Il rosso segna la tua mossa debole.',
  dialoguePrev: 'Indietro',
  dialogueNext: 'Avanti',
  dialogueSkip: 'Passa',
  objectionLesson:
    'Fermo la partita. Questa mossa lascia un vantaggio all’avversario. Il bordo rosso è sul pezzo che hai appena mosso. Il fantasma verde è la mossa che consiglio, e il bordo verde contorna il pezzo che deve partire. Puoi annullare e riprovare. Spiego perché.',
  trainingWelcome:
    'Qui si impara, senza i dieci minuti. Gioca una mossa. Se la trovo debole, fermo la partita: un bordo rosso contorna quel pezzo, e dei fantasmi mostrano il seguito. Verde, poi blu, poi giallo. Lo stesso colore contorna il pezzo che parte.',
  clockOn: 'Rimettere i dieci minuti',
  clockOff: 'Togliere i dieci minuti',
  noAnswer: 'Il modello non ha risposto.',
  coachModel: 'Modello',
  coachBase: 'Indirizzo del server',
  coachKey: 'Chiave di accesso, se il server la chiede',
  coachSave: 'Salva questo server',
  coachChecking: 'Ricerca di Ollama su questo computer…',
  coachReady: 'Ollama risponde. L’assistente lo usa, senza nulla da scrivere.',
  coachInstalled: 'Ollama è installato, ma non risponde ancora.',
  coachStart: 'Avvia Ollama',
  coachMissing: 'Ollama non è installato. Fa parlare l’assistente su questo computer, senza account.',
  coachInstall: 'Scarica Ollama',
  coachNoModels: 'Ollama non ha un modello. In un terminale: ollama pull llama3.2',
  coachOther: 'Usa un altro server',
  send: 'Inviare',
  openSettings: 'Aprire le impostazioni',
  close: 'Chiudere',
  resume: 'Riprendere',
  changeMode: 'Cambiare modo',
  leave: 'Lasciare il tavolo',
  home: 'Torna all’inizio',
  won: 'Vinto',
  lost: 'Perso',
  drawn: 'Patta',
  mateWhite: 'Il Bianco è sotto scacco matto.',
  mateBlack: 'Il Nero è sotto scacco matto.',
  flagWhite: 'Il Bianco ha perso a tempo.',
  flagBlack: 'Il Nero ha perso a tempo.',
  stalemateLine: 'Stallo. Nessuna mossa legale.',
  insufficientLine: 'Materiale insufficiente.',
  agreedLine: 'Patta accettata.',
  resignWhite: 'Il Bianco ha abbandonato.',
  resignBlack: 'Il Nero ha abbandonato.',
  resign: 'Abbandona',
  offerDraw: 'Proponi patta',
  acceptDraw: 'Accetta',
  refuseDraw: 'Rifiuta',
  drawOfferTitle: 'Proponi patta',
  drawOfferCpu: 'Il computer accetta se la valutazione è entro ±50 centipawns.',
  drawOfferPeer: 'L’altro campo vede questa offerta.',
  drawRefused: 'Patta rifiutata.',
  cancel: 'Annulla',
  lineDone: 'La linea è finita.',
  seeBoard: 'Vedi la scacchiera',
  replay: 'Ricomincia',
  result: 'Risultato',
  sound: 'Suono',
  sfx: 'Volume delle mosse',
  ambience: 'Ambiente',
  language: 'Lingua',
  controls: 'Controlli',
  grabLine: 'Prendere un pezzo e posarlo.',
  orbitLine: 'Girare intorno alla scacchiera, rotella compresa.',
  resetLine: 'Ricominciare la partita o la linea.',
  escapeKey: 'Esc',
  escapeLine: 'Pausa, o chiudere il pannello aperto.',
  example: 'esempio',
  wins: 'Vittorie',
  losses: 'Sconfitte',
  draws: 'Patte',
  streak: 'Serie',
  localGames: [
    'Vittoria · computer',
    'Sconfitta · stesso schermo',
    'Patta · in rete',
    'Vittoria · apertura',
    'Vittoria · computer',
  ],
  onlineGames: [
    'Vittoria · tavolo K7QM',
    'Sconfitta · tavolo M2LP',
    'Patta · tavolo Q9AD',
    'Vittoria · tavolo H4CE',
    'Sconfitta · tavolo B8NR',
  ],
  exampleRanks: 'Esempio — nessun server dei punteggi.',
  localTab: 'Locale',
  onlineTab: 'In rete',
  optionsHint: 'L’immagine si applica subito. Suono e assistente sono in Impostazioni.',
  setChoice: 'Ambiente',
  sets: { atelier: 'Atelier', salon: 'Salotto', club: 'Club', jardin: 'Giardino', terrasse: 'Terrazza' },
  preset: 'Predefinito',
  presets: { fluide: 'Fluido', equilibre: 'Equilibrato', qualite: 'Qualità', natif: 'Nativo' },
  image: 'Immagine',
  resolution: 'Risoluzione',
  resolutionNative: 'Nativo',
  textures: 'Texture dei pezzi',
  textureQuality: { low: 'Bassa', medium: 'Normale', high: 'Alta' },
  effects: 'Effetti',
  shadows: 'Ombre',
  shadowOff: 'Nessuna',
  shadowHard: 'Netta',
  shadowSoft: 'Morbida',
  upscale: 'Upscale',
  upscaleOff: 'Nessuno',
  upscaleQuality: 'Qualità',
  upscalePerformance: 'Prestazioni',
  ao: 'Occlusione ambientale',
  reflections: 'Riflessi della scacchiera',
  bloom: 'Bloom',
  render: 'Resa',
  fps: 'fps',
  saves: 'Salvataggi',
  resumeGame: 'Riprendi la partita',
  save: 'Salva',
  saved: 'Partita salvata',
  savesHint: 'L’interruzione è la partita chiusa. Le altre sono quelle chieste in pausa.',
  interrupted: 'Partita interrotta',
  requested: 'Richiesti',
  restore: 'Ripristina',
  discard: 'Scarta',
  remove: 'Elimina',
  noSaves: 'Nessuna partita salvata.',
  p2p: { waiting: 'In attesa', connecting: 'Connessione', connected: 'Connesso', disconnected: 'Disconnesso' },
};
