/**
 * @file ja.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Japanese shell copy.
 */

import type { ShellCopy } from './types';

export const JA: ShellCopy = {
  play: '対局',
  ranks: '順位',
  options: 'オプション',
  about: '情報',
  aboutVersion: 'バージョン',
  aboutNote: 'リリースノート',
  aboutNoteMissing: 'この版のノートはリリースのときに書かれます。',
  aboutCredits: 'クレジット',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'プロプライエタリソフトウェア。無断転載を禁じます。',
  settings: '設定',
  settingsHint: '音、言語、操作、アシスタントの接続。',
  modes: 'モード',
  modeCards: {
    cpu: { title: 'コンピューター対戦', blurb: 'ヒューリスティックとの対局。' },
    hotseat: { title: '同じ画面で二人', blurb: 'マウスを交代する。' },
    local: { title: 'このパソコンで', blurb: 'このアプリの別ウィンドウ。' },
    online: { title: 'オンライン', blurb: '卓を作るか、参加する。' },
    learn: { title: '学習', blurb: '短い ECO の手順。' },
    training: { title: 'トレーニング', blurb: '止めて、見直して、やり直す。' },
  },
  color: '色',
  white: '白',
  black: '黒',
  level: 'レベル',
  line: '手順',
  openings: {
    C50: 'イタリアン・ゲーム',
    C60: 'ルイ・ロペス',
    C44: 'スコッチ・ゲーム',
    B20: 'シシリアン・ディフェンス',
    C00: 'フレンチ・ディフェンス',
    B10: 'カロ・カン',
    D06: 'クイーンズ・ギャンビット',
    E60: 'キングス・インディアン',
  },
  begin: '開始',
  openLobby: 'ロビーを開く',
  back: '戻る',
  backModes: 'モードに戻る',
  lobby: 'オンラインのロビー',
  colorHint: '色はここで選ぶ。客はもう一方を持つ。',
  create: '卓を作る',
  join: '参加',
  copy: 'コピー',
  refused: 'コードが拒否されました',
  tableMissing: '卓が見つからないか、満席です',
  whiteTurn: '白の手番',
  blackTurn: '黒の手番',
  thinking: 'コンピューターが考えています…',
  learn: '学習',
  assistant: 'アシスタント',
  pause: '一時停止',
  grab: 'つかむ',
  orbit: '回す',
  reset: 'やり直す',
  coachBanner: '解説であり、一手ではない。アシスタントは指さない。',
  noModel: 'モデルは接続されていません。',
  explain: '局面を説明する',
  hint: 'ヒント',
  ask: '自由な質問',
  stop: '停止',
  undoMove: '自分の手を取り消す',
  horizon: '先読み',
  mistake: '自分の誤りを説明する',
  strategy: '方針',
  objection: '異議あり！',
  objectionLine: 'それが最もきれいな一手ではありません。',
  ghostHint:
    '緑のゴーストはあなたの次の手です。青もあなた、その次が黄です。さらに先は橙、それから紫です。縁はあなたの駒を囲みます。赤はあなたの弱い手です。',
  dialoguePrev: '前へ',
  dialogueNext: '次へ',
  dialogueSkip: 'スキップ',
  objectionLesson:
    '対局を止めます。その手は相手に得を残します。赤い縁は、今指した駒にあります。緑のゴーストが勧める手で、緑の縁が動くべき駒を囲みます。取り消してやり直せます。理由を説明します。',
  trainingWelcome:
    'ここは学習です。十分の時計はありません。一手指してください。弱いと思うと対局を止めます。赤い縁がその駒を囲み、ゴーストが続きを示します。緑、次に青、次に黄。同じ色の縁が動く駒を囲みます。',
  clockOn: '十分を戻す',
  clockOff: '十分を切る',
  noAnswer: 'モデルは答えませんでした。',
  coachModel: 'モデル',
  coachBase: 'サーバーのアドレス',
  coachKey: 'アクセスキー。サーバーが求める場合だけ',
  coachSave: 'このサーバーを保存',
  coachChecking: 'このパソコンで Ollama を探しています…',
  coachReady: 'Ollama が応答しています。アシスタントは入力なしで使います。',
  coachInstalled: 'Ollama は入っていますが、まだ応答しません。',
  coachStart: 'Ollama を起動',
  coachMissing: 'Ollama は入っていません。アカウントなしで、このパソコンのアシスタントが話せるようになります。',
  coachInstall: 'Ollama をダウンロード',
  coachNoModels: 'Ollama にモデルがありません。ターミナルで：ollama pull llama3.2',
  coachOther: '別のサーバーを使う',
  send: '送る',
  openSettings: '設定を開く',
  close: '閉じる',
  resume: '再開',
  changeMode: 'モードを変える',
  leave: '卓を離れる',
  home: '最初の画面へ',
  won: '勝ち',
  lost: '負け',
  drawn: '引き分け',
  mateWhite: '白がチェックメイトです。',
  mateBlack: '黒がチェックメイトです。',
  flagWhite: '白は時間切れです。',
  flagBlack: '黒は時間切れです。',
  stalemateLine: 'ステイルメイト。合法手がありません。',
  insufficientLine: '戦力不足。',
  agreedLine: '引き分け成立。',
  resignWhite: '白が投了しました。',
  resignBlack: '黒が投了しました。',
  resign: '投了',
  offerDraw: '引き分けを提案',
  acceptDraw: '受ける',
  refuseDraw: '断る',
  drawOfferTitle: '引き分けを提案',
  drawOfferCpu: '評価が±50センチポーン以内ならコンピュータは受けます。',
  drawOfferPeer: '相手側にこの提案が表示されます。',
  drawRefused: '引き分けを拒否されました。',
  cancel: 'キャンセル',
  lineDone: 'この手順は終わりました。',
  seeBoard: '盤面を見る',
  replay: 'もう一局',
  result: '結果',
  sound: '音',
  sfx: '着手の音量',
  ambience: '環境音',
  language: '言語',
  controls: '操作',
  grabLine: '駒をつかんで置く。',
  orbitLine: '盤の周りを回す。ホイールも含む。',
  resetLine: '対局か手順をやり直す。',
  escapeKey: 'Esc',
  escapeLine: '一時停止、または開いているパネルを閉じる。',
  example: '例',
  wins: '勝ち',
  losses: '負け',
  draws: '引き分け',
  streak: '連勝',
  localGames: [
    '勝ち · コンピューター',
    '負け · 同じ画面',
    '引き分け · オンライン',
    '勝ち · 序盤',
    '勝ち · コンピューター',
  ],
  onlineGames: [
    '勝ち · 卓 K7QM',
    '負け · 卓 M2LP',
    '引き分け · 卓 Q9AD',
    '勝ち · 卓 H4CE',
    '負け · 卓 B8NR',
  ],
  exampleRanks: '例 — 成績サーバーはない。',
  localTab: 'ローカル',
  onlineTab: 'オンライン',
  optionsHint: '画面はすぐに変わる。音とアシスタントは設定にある。',
  setChoice: '雰囲気',
  sets: { atelier: 'アトリエ', salon: 'サロン', club: 'クラブ', jardin: '庭', terrasse: 'テラス' },
  preset: 'プリセット',
  presets: { fluide: '軽快', equilibre: 'バランス', qualite: '高品質', natif: 'ネイティブ' },
  image: '画面',
  resolution: '解像度',
  resolutionNative: 'ネイティブ',
  textures: '駒のテクスチャ',
  textureQuality: { low: '低', medium: '標準', high: '高' },
  effects: '効果',
  shadows: '影',
  shadowOff: 'なし',
  shadowHard: 'ハード',
  shadowSoft: 'ソフト',
  upscale: 'アップスケール',
  upscaleOff: 'なし',
  upscaleQuality: '品質',
  upscalePerformance: '性能',
  ao: '環境遮蔽',
  reflections: '盤の反射',
  bloom: 'ブルーム',
  render: '描画',
  fps: 'fps',
  saves: 'セーブ',
  resumeGame: '対局を再開',
  save: '保存',
  saved: '対局を保存しました',
  savesHint: '中断は閉じた対局です。ほかは一時停止で保存したものです。',
  interrupted: '中断した対局',
  requested: '保存済み',
  restore: '復元',
  discard: '捨てる',
  remove: '削除',
  noSaves: '保存した対局はありません。',
  p2p: { waiting: '待機', connecting: '接続中', connected: '接続済み', disconnected: '切断' },
};
