/**
 * @file ru.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Russian shell copy.
 */

import type { ShellCopy } from './types';

export const RU: ShellCopy = {
  play: 'Играть',
  ranks: 'Рейтинги',
  options: 'Параметры',
  about: 'О программе',
  aboutVersion: 'Версия',
  aboutNote: 'Примечание к выпуску',
  aboutNoteMissing: 'Примечание к этой версии пишется вместе с выпуском.',
  aboutCredits: 'Авторы',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: 'Проприетарное программное обеспечение. Все права защищены.',
  settings: 'Настройки',
  settingsHint: 'Звук, язык, управление и подключение помощника.',
  modes: 'Режимы',
  modeCards: {
    cpu: { title: 'Против компьютера', blurb: 'Партия против эвристики.' },
    hotseat: { title: 'Вдвоём, один экран', blurb: 'Мышь передают друг другу.' },
    local: { title: 'На этом компьютере', blurb: 'Второе окно этого приложения.' },
    online: { title: 'По сети', blurb: 'Создать стол или войти.' },
    learn: { title: 'Обучение', blurb: 'Короткая линия ECO.' },
  },
  color: 'Цвет',
  white: 'Белые',
  black: 'Чёрные',
  level: 'Уровень',
  line: 'Линия',
  openings: {
    C50: 'Итальянская партия',
    C60: 'Испанская партия',
    C44: 'Шотландская партия',
    B20: 'Сицилианская защита',
    C00: 'Французская защита',
    B10: 'Защита Каро-Канн',
    D06: 'Ферзевый гамбит',
    E60: 'Староиндийская защита',
  },
  begin: 'Начать',
  openLobby: 'Открыть зал',
  back: 'Назад',
  backModes: 'К режимам',
  lobby: 'Сетевой зал',
  colorHint: 'Цвет выбирают здесь. Гость берёт другой.',
  create: 'Создать стол',
  join: 'Войти',
  copy: 'Копировать',
  refused: 'Код отклонён',
  whiteTurn: 'Ход белых',
  blackTurn: 'Ход чёрных',
  thinking: 'Компьютер думает…',
  learn: 'Обучение',
  assistant: 'Помощник',
  pause: 'Пауза',
  grab: 'взять',
  orbit: 'вращать',
  reset: 'заново',
  coachBanner: 'Комментарий, не ход. Помощник не играет.',
  noModel: 'Модель не подключена.',
  explain: 'Объяснить позицию',
  hint: 'Подсказка',
  ask: 'Свободный вопрос',
  send: 'Отправить',
  openSettings: 'Открыть настройки',
  close: 'Закрыть',
  resume: 'Продолжить',
  changeMode: 'Сменить режим',
  leave: 'Покинуть стол',
  home: 'На главный экран',
  sound: 'Звук',
  sfx: 'Громкость ходов',
  ambience: 'Фон',
  language: 'Язык',
  controls: 'Управление',
  grabLine: 'Взять фигуру и поставить её.',
  orbitLine: 'Крутить камеру вокруг доски, вместе с колёсиком.',
  resetLine: 'Начать партию или линию заново.',
  escapeKey: 'Esc',
  escapeLine: 'Пауза или закрыть открытую панель.',
  example: 'пример',
  wins: 'Победы',
  losses: 'Поражения',
  draws: 'Ничьи',
  streak: 'Серия',
  localGames: [
    'Победа · компьютер',
    'Поражение · один экран',
    'Ничья · по сети',
    'Победа · дебют',
    'Победа · компьютер',
  ],
  onlineGames: [
    'Победа · стол K7QM',
    'Поражение · стол M2LP',
    'Ничья · стол Q9AD',
    'Победа · стол H4CE',
    'Поражение · стол B8NR',
  ],
  exampleRanks: 'Пример — сервера очков нет.',
  localTab: 'Здесь',
  onlineTab: 'По сети',
  optionsHint: 'Картинка меняется сразу. Звук и помощник — в Настройках.',
  preset: 'Профиль',
  presets: { fluide: 'Плавно', equilibre: 'Баланс', qualite: 'Качество', natif: 'Экран' },
  image: 'Изображение',
  resolution: 'Разрешение',
  resolutionNative: 'Экран',
  textures: 'Текстуры фигур',
  textureQuality: { low: 'Низкие', medium: 'Обычные', high: 'Высокие' },
  effects: 'Эффекты',
  shadows: 'Тени',
  ao: 'Затенение',
  reflections: 'Отражения доски',
  bloom: 'Свечение',
  render: 'Кадр',
  fps: 'кадр/с',
  saves: 'Сохранения',
  resumeGame: 'Продолжить партию',
  save: 'Сохранить',
  saved: 'Партия сохранена',
  savesHint: 'Прерванная — это закрытая партия. Остальные запрошены в паузе.',
  interrupted: 'Прерванная партия',
  requested: 'Запрошенные',
  restore: 'Восстановить',
  discard: 'Убрать',
  remove: 'Удалить',
  noSaves: 'Нет сохранённых партий.',
  p2p: { waiting: 'Ожидание', connecting: 'Соединение', connected: 'Подключён', disconnected: 'Отключён' },
};
