/**
 * @file zh.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Simplified Chinese shell copy.
 */

import type { ShellCopy } from './types';

export const ZH: ShellCopy = {
  play: '开始',
  ranks: '排名',
  options: '选项',
  about: '关于',
  aboutVersion: '版本',
  aboutNote: '发行说明',
  aboutNoteMissing: '此版本的说明将在发布时撰写。',
  aboutCredits: '署名',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: '专有软件。保留所有权利。',
  settings: '设置',
  settingsHint: '声音、语言、操作，以及助手的连接。',
  modes: '模式',
  modeCards: {
    cpu: { title: '对电脑', blurb: '与启发式引擎对局。' },
    hotseat: { title: '双人同屏', blurb: '轮流使用鼠标。' },
    local: { title: '在这台电脑上', blurb: '本应用的第二个窗口。' },
    online: { title: '在线', blurb: '创建或加入牌桌。' },
    learn: { title: '学习', blurb: '一条简短的 ECO 开局。' },
    training: { title: '训练', blurb: '停下、复盘、再走。' },
  },
  color: '颜色',
  white: '白方',
  black: '黑方',
  level: '等级',
  line: '线路',
  openings: {
    C50: '意大利开局',
    C60: '西班牙开局',
    C44: '苏格兰开局',
    B20: '西西里防御',
    C00: '法兰西防御',
    B10: '卡罗-卡恩',
    D06: '后翼弃兵',
    E60: '王翼印度防御',
  },
  begin: '开始对局',
  openLobby: '打开大厅',
  back: '返回',
  backModes: '返回模式',
  lobby: '在线大厅',
  colorHint: '颜色在这里选定。来宾执另一方。',
  create: '创建牌桌',
  join: '加入',
  copy: '复制',
  refused: '代码无效',
  tableMissing: '棋桌不存在或已满',
  whiteTurn: '白方走棋',
  blackTurn: '黑方走棋',
  thinking: '电脑正在思考…',
  learn: '学习',
  assistant: '助手',
  pause: '暂停',
  grab: '拿起',
  orbit: '环视',
  reset: '重来',
  coachBanner: '只作解说，不是一步棋。助手不下棋。',
  noModel: '尚未连接模型。',
  explain: '解说局面',
  hint: '提示',
  ask: '自由提问',
  stop: '停止',
  undoMove: '撤销我的着法',
  horizon: '视野',
  mistake: '解释我的失误',
  strategy: '策略',
  objection: '异议！',
  ghostHint: '绿色幽灵是你的下一步。蓝色也是你的，然后是黄色。再往后是橙色，然后是紫色。轮廓标出你要走的棋子。红色标出你的弱着。',
  dialoguePrev: '上一句',
  dialogueNext: '下一句',
  dialogueSkip: '跳过',
  objectionLesson:
    '我先停下棋局。这一步把优势让给了对方。红色轮廓在你刚走的棋子上。绿色幽灵是我建议的着法，绿色轮廓标出该走的棋子。可以撤销再试。我来说明原因。',
  trainingWelcome:
    '这里是学习，没有那十分钟。走一步。如果我觉得它不好，我会停下：红色轮廓圈住这枚棋子，幽灵显示后续。先绿，再蓝，再黄。同色轮廓标出要走的棋子。',
  clockOn: '重新打开十分钟',
  clockOff: '关掉十分钟',
  noAnswer: '模型没有回答。',
  coachModel: '模型',
  coachBase: '服务器地址',
  coachKey: '访问密钥，仅当服务器要求时填写',
  coachSave: '保存此服务器',
  coachChecking: '正在这台电脑上查找 Ollama…',
  coachReady: 'Ollama 已响应。助手会直接使用它，无需填写。',
  coachInstalled: '已安装 Ollama，但尚未响应。',
  coachStart: '启动 Ollama',
  coachMissing: '尚未安装 Ollama。它让助手在这台电脑上说话，无需账号。',
  coachInstall: '下载 Ollama',
  coachNoModels: 'Ollama 还没有模型。在终端中运行：ollama pull llama3.2',
  coachOther: '使用其他服务器',
  send: '发送',
  openSettings: '打开设置',
  close: '关闭',
  resume: '继续',
  changeMode: '更换模式',
  leave: '离开牌桌',
  home: '回到首页',
  sound: '声音',
  sfx: '走棋音量',
  ambience: '环境音量',
  language: '语言',
  controls: '操作',
  grabLine: '拿起棋子，再放下。',
  orbitLine: '绕棋盘转动，包括滚轮。',
  resetLine: '重新开始对局或线路。',
  escapeKey: 'Esc',
  escapeLine: '暂停，或关闭打开的面板。',
  example: '示例',
  wins: '胜',
  losses: '负',
  draws: '和',
  streak: '连胜',
  localGames: ['胜 · 电脑', '负 · 同屏', '和 · 在线', '胜 · 开局', '胜 · 电脑'],
  onlineGames: ['胜 · 牌桌 K7QM', '负 · 牌桌 M2LP', '和 · 牌桌 Q9AD', '胜 · 牌桌 H4CE', '负 · 牌桌 B8NR'],
  exampleRanks: '示例 — 没有积分服务器。',
  localTab: '本地',
  onlineTab: '在线',
  optionsHint: '画面立即生效。声音和助手在设置里。',
  setChoice: '氛围',
  sets: { atelier: '工作室', salon: '客厅', club: '俱乐部' },
  preset: '预设',
  presets: { fluide: '流畅', equilibre: '均衡', qualite: '质量', natif: '原生' },
  image: '画面',
  resolution: '分辨率',
  resolutionNative: '原生',
  textures: '棋子纹理',
  textureQuality: { low: '低', medium: '标准', high: '高' },
  effects: '效果',
  shadows: '阴影',
  shadowOff: '无',
  shadowHard: '硬阴影',
  shadowSoft: '软阴影',
  upscale: '放大',
  upscaleOff: '关闭',
  upscaleQuality: '质量',
  upscalePerformance: '性能',
  ao: '环境光遮蔽',
  reflections: '棋盘反射',
  bloom: '泛光',
  render: '渲染',
  fps: '帧/秒',
  saves: '存档',
  resumeGame: '继续对局',
  save: '保存',
  saved: '对局已保存',
  savesHint: '中断的是关掉的那盘。其余是暂停时保存的。',
  interrupted: '中断的对局',
  requested: '已保存',
  restore: '恢复',
  discard: '丢弃',
  remove: '删除',
  noSaves: '没有保存的对局。',
  p2p: { waiting: '等待中', connecting: '连接中', connected: '已连接', disconnected: '已断开' },
};
