/**
 * @file zh.ts
 * @project w3dts
 * @author Cyril TARRIET
 * @description Simplified Chinese shell copy.
 */

import type { ShellCopy } from './types';

export const ZH: ShellCopy = {
  play: '开始',
  ranks: '排名',
  options: '选项',
  about: '关于',
  aboutVersion: '版本',
  aboutNote: '发行说明',
  aboutNoteMissing: '此版本的说明将在发布时撰写。',
  aboutCredits: '署名',
  aboutCopyright: 'ChessMaster & W3DTS copyright Cyril TARRIET',
  aboutProprietary: '专有软件。保留所有权利。',
  settings: '设置',
  settingsHint: '声音、语言、操作，以及助手的连接。',
  modes: '模式',
  modeCards: {
    cpu: { title: '对电脑', blurb: '与启发式引擎对局。' },
    hotseat: { title: '双人同屏', blurb: '轮流使用鼠标。' },
    local: { title: '在这台电脑上', blurb: '本应用的第二个窗口。' },
    online: { title: '在线', blurb: '创建或加入牌桌。' },
    learn: { title: '学习', blurb: '一条简短的 ECO 开局。' },
  },
  color: '颜色',
  white: '白方',
  black: '黑方',
  level: '等级',
  line: '线路',
  openings: {
    C50: '意大利开局',
    C60: '西班牙开局',
    C44: '苏格兰开局',
    B20: '西西里防御',
    C00: '法兰西防御',
    B10: '卡罗-卡恩',
    D06: '后翼弃兵',
    E60: '王翼印度防御',
  },
  begin: '开始对局',
  openLobby: '打开大厅',
  back: '返回',
  backModes: '返回模式',
  lobby: '在线大厅',
  colorHint: '颜色在这里选定。来宾执另一方。',
  create: '创建牌桌',
  join: '加入',
  copy: '复制',
  refused: '代码无效',
  whiteTurn: '白方走棋',
  blackTurn: '黑方走棋',
  thinking: '电脑正在思考…',
  learn: '学习',
  assistant: '助手',
  pause: '暂停',
  grab: '拿起',
  orbit: '环视',
  reset: '重来',
  coachBanner: '只作解说，不是一步棋。助手不下棋。',
  noModel: '尚未连接模型。',
  explain: '解说局面',
  hint: '提示',
  ask: '自由提问',
  send: '发送',
  openSettings: '打开设置',
  close: '关闭',
  resume: '继续',
  changeMode: '更换模式',
  leave: '离开牌桌',
  home: '回到首页',
  sound: '声音',
  sfx: '走棋音量',
  ambience: '环境音量',
  language: '语言',
  controls: '操作',
  grabLine: '拿起棋子，再放下。',
  orbitLine: '绕棋盘转动，包括滚轮。',
  resetLine: '重新开始对局或线路。',
  escapeKey: 'Esc',
  escapeLine: '暂停，或关闭打开的面板。',
  example: '示例',
  wins: '胜',
  losses: '负',
  draws: '和',
  streak: '连胜',
  localGames: ['胜 · 电脑', '负 · 同屏', '和 · 在线', '胜 · 开局', '胜 · 电脑'],
  onlineGames: ['胜 · 牌桌 K7QM', '负 · 牌桌 M2LP', '和 · 牌桌 Q9AD', '胜 · 牌桌 H4CE', '负 · 牌桌 B8NR'],
  exampleRanks: '示例 — 没有积分服务器。',
  localTab: '本地',
  onlineTab: '在线',
  optionsHint: '画面立即生效。声音和助手在设置里。',
  preset: '预设',
  presets: { fluide: '流畅', equilibre: '均衡', qualite: '质量', natif: '原生' },
  image: '画面',
  resolution: '分辨率',
  resolutionNative: '原生',
  textures: '棋子纹理',
  textureQuality: { low: '低', medium: '标准', high: '高' },
  effects: '效果',
  shadows: '阴影',
  ao: '环境光遮蔽',
  reflections: '棋盘反射',
  bloom: '泛光',
  render: '渲染',
  fps: '帧/秒',
  saves: '存档',
  resumeGame: '继续对局',
  save: '保存',
  saved: '对局已保存',
  savesHint: '中断的是关掉的那盘。其余是暂停时保存的。',
  interrupted: '中断的对局',
  requested: '已保存',
  restore: '恢复',
  discard: '丢弃',
  remove: '删除',
  noSaves: '没有保存的对局。',
  p2p: { waiting: '等待中', connecting: '连接中', connected: '已连接', disconnected: '已断开' },
};
