/**
 * @file postprocess_master_node.wgsl
 * @description Logic snippet for PostProcessMasterNode — assigns final fullscreen color.
 */

// --- Post-process Master (Generated by PostProcessMasterNode) ---
let final_color = {{color}};
